version: '3'
services:
  authentication_backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: 'authentication_backend'
    working_dir: '/home/guest/authentication/backend'
    tty: true
    ports:
      - 8000:8000
    volumes:
      - $PWD/backend:/home/guest/authentication/backend
    depends_on: 
      # authentication_db:
      #   condition: service_healthy
      # - waitfordb
      - authentication_db
    environment:
      TZ: Asia/Tokyo
    env_file:
      - ./.env
    # command: bash
    # command: bash -c "cd /home/guest/authentication/backend && alembic upgrade head"
    command: ["./scripts/up.sh"]
    networks:
      - authentication-network

  authentication_db:
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    container_name: 'authentication_db'
    platform: linux/x86_64 
    restart: always
    tty: true
    env_file:
      - ./.env
    volumes:
      - $PWD/db/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - dbdata:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
      #  - $PWD/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports: 
      - 3308:3308
    networks:
      - authentication-network

  authentication_frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    container_name: 'authentication_frontend'
    tty: true
    volumes:
      - $PWD/frontend:/home/guest/authentication/frontend
    depends_on: 
      - authentication_backend
    command: sh
    ports:
      - 3000:3000
    networks:
      - authentication-network

  # waitfordb:
  #     image: dadarek/wait-for-dependencies
  #     depends_on:
  #       - authentication_db
  #     command: authentication_db:3308
      

volumes:
 dbdata:

networks:
  default:
    external:
      name: bridge
  authentication-network:
    name: authentication-network
    driver: bridge
    external: true
