DROP DATABASE IF EXISTS authinfo;
CREATE DATABASE authinfo;
USE authinfo;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
)DEFAULT CHARACTER
  SET=utf8;