"""add contextinfo

Revision ID: b4f5e4f2a1a2
Revises: d121c966fa95
Create Date: 2022-12-19 04:04:18.102681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f5e4f2a1a2'
down_revision = 'd121c966fa95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contextinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('twitterID', sa.String(length=50), nullable=True),
    sa.Column('when', sa.String(length=50), nullable=True),
    sa.Column('where', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contextinfo_id'), 'contextinfo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contextinfo_id'), table_name='contextinfo')
    op.drop_table('contextinfo')
    # ### end Alembic commands ###
